apiVersion: v1
kind: Namespace
metadata:
  name: ns-portainer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-portainer
  namespace: ns-portainer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-portainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sa-portainer
  namespace: ns-portainer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: portainer
  namespace: ns-portainer
spec:
  selector:
    matchLabels:
      run: portainer
  template:
    metadata:
      labels:
        run: portainer
    spec:
      serviceAccountName: sa-portainer
      containers:
      - name: portainer
        image: portainer/base
        command: ["/app/portainer"]
        args: ["--no-analytics", "--template-file","/app/templates.json"]
        ports:
        - containerPort: 9000
          hostPort: 9000
        volumeMounts:
        - mountPath: /app
          name: portainer-dist
      volumes:
      - name: portainer-dist
        hostPath:
          path: /portainer/app
          type: Directory
